#!/bin/bash

: ${ENV:=development}

buildApp () {
	NODE_ENV=$ENV BUILD_MODE=dist npm run build;
};

cd $SCRATCH_GUI_PATH;
npm install;

cd $SCRATCH_VM_PATH;
npm install;
npm link;
buildApp
cd $SCRATCH_GUI_PATH;
npm link scratch-vm;
buildApp
cd gem;
rake wrapper:wrap;
echo "Scratch built :D";
