require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task :default => :spec

namespace :wrapper do
  desc 'Wrap styles assets into this gem'
  task wrap: :clean do
    # readme
    cp_r '../README.md', 'README.md'

    #  javascript assets
    cp_r '../build/lib.min.js', 'app/assets/javascripts'
    cp_r '../build/gui.js', 'app/assets/javascripts'

  end

  task :clean do
    rm_rf 'app'
    mkdir_p 'app/assets/javascripts'
  end
end
